# docker-compose.yml
version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_NAME=name
      - REDIS_HOST=redis
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: .
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_NAME=name
      - REDIS_HOST=redis
    command: celery -A zibal_project worker -l info

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo_data:
